"""Backend-independent trajectory row schema and store protocol.

`TrajectoryRow` is the one, single-observation record shape every
persisted trajectory row uses (see `fim.model.state.ModelState.to_rows`
for how a state turns into a batch of these), and `TrajectoryStore` is
the shared interface both `fim.persistence.jsonl_store.
JSONLTrajectoryStore` (the real, file-backed store) and
`InMemoryTrajectoryStore`, below (a lighter-weight stand-in for
library calls and tests that never need an actual file), implement —
so `fim.engine`'s run loop can write to either without knowing which
one it actually has.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping
from typing import Any, Protocol, TypedDict

from fim.model.identifiers import parse_bounded_frequency


class TrajectoryRow(TypedDict):
    """One nonzero allele-frequency observation.

    One row means one specific allele, at one specific locus, in one
    specific deme, at one specific generation, had a nonzero frequency
    — an allele that is entirely absent from a given deme/locus/
    generation simply has no row at all (see `fim.model.state.
    ModelState`'s own docstring for why this sparse representation is
    used). `run_id`, `generation`, `deme`, and `locus_id` together
    identify *which* observation this is; `allele_id` and `frequency`
    are the observation itself.
    """

    run_id: str
    generation: int
    deme: int
    locus_id: int
    allele_id: int
    frequency: float


class TrajectoryStore(Protocol):
    """Incrementally persist and iterate long-form trajectory rows.

    A "protocol" here means any object with these two methods — this
    class is never instantiated itself; both `InMemoryTrajectoryStore`,
    below, and `fim.persistence.jsonl_store.JSONLTrajectoryStore`
    satisfy it, so a caller can be written against this one shared
    interface regardless of which concrete store it is actually given.
    """

    def write_generation(
        self,
        run_id: str,
        generation: int,
        rows: Iterable[Mapping[str, Any]],
    ) -> None:
        """Persist all rows for one generation."""
        ...

    def read(self, run_id: str) -> Iterator[TrajectoryRow]:
        """Yield rows for one run in stored order."""
        ...


class InMemoryTrajectoryStore:
    """Store trajectories in memory for library calls and focused tests.

    Implements the same `TrajectoryStore` protocol as `fim.persistence.
    jsonl_store.JSONLTrajectoryStore`, but keeps every row in an
    ordinary Python list rather than writing to a file — used whenever
    a caller (a unit test, or a library user who only wants the final
    result and does not care about a persisted trajectory file) has no
    need to actually write anything to disk.
    """

    def __init__(self) -> None:
        """Initialize an empty store."""
        self._rows: list[TrajectoryRow] = []

    def write_generation(
        self,
        run_id: str,
        generation: int,
        rows: Iterable[Mapping[str, Any]],
    ) -> None:
        """Append one validated generation."""
        generation_rows = [
            normalize_row(row, run_id=run_id, generation=generation) for row in rows
        ]
        if not generation_rows:
            raise ValueError("a generation must contain at least one row")
        self._rows.extend(generation_rows)

    def read(self, run_id: str) -> Iterator[TrajectoryRow]:
        """Yield rows matching ``run_id`` in insertion order."""
        return (row.copy() for row in self._rows if row["run_id"] == run_id)


def normalize_row(
    row: Mapping[str, Any],
    *,
    run_id: str | None = None,
    generation: int | None = None,
) -> TrajectoryRow:
    """Validate and normalize one public-schema trajectory row.

    "Public schema" means this is the one row shape a trajectory file
    is allowed to contain — exactly the six `TrajectoryRow` fields,
    nothing missing and nothing extra — so a hand-edited or externally
    produced row is checked against the identical rules a row
    generated by the simulator itself already satisfies. When `run_id`
    and/or `generation` are supplied, the row's own values for those
    fields are additionally cross-checked against them (used by
    `write_generation`, below, and by `fim.persistence.jsonl_store.
    JSONLTrajectoryStore.write_generation`, to catch a row that claims
    to belong to a different run or generation than the batch it was
    handed in).

    Args:
        row: Mapping containing all six schema fields.
        run_id: Optional required run identity.
        generation: Optional required generation.

    Returns:
        A typed row with primitive values.
    """
    expected = {
        "run_id",
        "generation",
        "deme",
        "locus_id",
        "allele_id",
        "frequency",
    }
    missing = expected - set(row)
    if missing:
        names = ", ".join(sorted(missing))
        raise ValueError(f"trajectory row is missing: {names}")
    extra = set(row) - expected
    if extra:
        names = ", ".join(sorted(extra))
        raise ValueError(f"trajectory row has unknown fields: {names}")

    normalized_run_id = _string_field(row, "run_id")
    normalized_generation = _int_field(row, "generation", minimum=0)
    normalized = TrajectoryRow(
        run_id=normalized_run_id,
        generation=normalized_generation,
        deme=_int_field(row, "deme", minimum=1),
        locus_id=_int_field(row, "locus_id", minimum=1),
        allele_id=_int_field(row, "allele_id", minimum=0),
        frequency=_frequency_field(row),
    )
    if run_id is not None and normalized_run_id != run_id:
        raise ValueError(f"row run_id {normalized_run_id!r} does not match {run_id!r}")
    if generation is not None and normalized_generation != generation:
        raise ValueError(
            f"row generation {normalized_generation} does not match {generation}"
        )
    return normalized


def _frequency_field(row: Mapping[str, Any]) -> float:
    """Read one positive finite row frequency.

    Delegates to `fim.model.identifiers.parse_bounded_frequency`, the
    same rule `fim.model.state.ModelState.from_rows` uses for the
    identical row schema (S5/S6) — one shared validator for both
    readers of one row schema, rather than two independently
    maintained rules that can silently drift apart.
    """
    return parse_bounded_frequency(
        "trajectory row frequency must be in (0, 1]", row["frequency"]
    )


def _int_field(
    row: Mapping[str, Any],
    key: str,
    *,
    minimum: int,
) -> int:
    """Read one bounded integer row field."""
    raw_value = row[key]
    if isinstance(raw_value, bool) or not isinstance(raw_value, int):
        raise ValueError(f"trajectory row {key} must be an integer")
    if raw_value < minimum:
        raise ValueError(f"trajectory row {key} must be at least {minimum}")
    return int(raw_value)


def _string_field(row: Mapping[str, Any], key: str) -> str:
    """Read one nonempty string row field."""
    raw_value = row[key]
    if not isinstance(raw_value, str) or not raw_value:
        raise ValueError(f"trajectory row {key} must be a nonempty string")
    return raw_value
