"""Derive the Dear-Nolan high-migration example's starting state.

The high-migration Dear-Nolan case is a stationarity check: it starts the
population at the equilibrium the identity recursion predicts, then runs a
short horizon to see whether the simulator holds it. A starting state like
that cannot be guessed by hand, so this script derives it and writes it into
`config.yaml` as an explicit `p_0` table. The run itself is an ordinary
`fim run` of that file:

```console
python3 doc/examples/dear-nolan-high/reproduce.py --check   # config is current
python3 doc/examples/dear-nolan-high/reproduce.py --write   # rewrite config
fim run doc/examples/dear-nolan-high/config.yaml \
    --output results/dear-nolan-high --quiet
```

The derivation keeps every step visible:

1. compute the fixed-point identities for the biological scenario,
2. build the near-equilibrium starting state from them,
3. write the configuration that runs the short validation experiment
   (five replicates of 30 generations each, the same experiment as
   `test/validation/test_simulator_equilibrium.py`'s Dear-Nolan
   high-migration test).

Without an option, the script prints the configuration and the predicted
equilibrium values without changing any file.
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from collections.abc import Sequence
from pathlib import Path
from types import ModuleType
from typing import Any

import yaml

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
TEST_PATH = ROOT / "test" / "validation" / "test_simulator_equilibrium.py"
CONFIG_PATH = HERE / "config.yaml"

# The scenario's model parameters (Dear-Nolan high migration).
POPULATION_SIZE = 2000
DEMES = 100
MIGRATION = 0.01
MUTATION = 0.001
SEED = 992000
SHARED_ALLELES = 41

# The validation experiment: a fixed horizon, never an early stop.
HORIZON = 30
REPLICATES = 5
LOCUS_LENGTH = 400

# Labels and comments that open the file; the model keys follow.
HEADER = """\
name: Dear-Nolan high migration
description: >-
  One hundred well-connected islands started at their predicted equilibrium,
  checked over 30 generations for staying there.
class: calibration-dear-nolan
_read_only: true  # marks the shipped copy read-only; delete it in your own copy
# Generated by doc/examples/dear-nolan-high/reproduce.py; edit that script,
# not this file. `p_0` is the derived near-equilibrium start: 41 alleles
# shared by every island plus 22 private to each one. The convergence keys
# make a fixed 30-generation horizon: each replicate burns in for one
# generation, averages for 29 more and stops (a fixed window, no precision
# check).
"""


def build_config(module: ModuleType) -> dict[str, Any]:
    """Return the model keys of the example's configuration.

    Args:
        module: The imported equilibrium-validation test module, which
            owns the fixed-point and starting-state helpers.

    Returns:
        The configuration mapping, without its labels, in file order.
    """
    within_star, between_star = module._identity_fixed_point(
        population_size=POPULATION_SIZE, m=MIGRATION, mu=MUTATION, d=DEMES
    )
    start = module._dn2_equilibrium_start(
        within_fixed_point=within_star,
        between_fixed_point=between_star,
        d=DEMES,
        shared_count=SHARED_ALLELES,
    )
    p_0 = [
        [
            {int(allele): float(frequency) for allele, frequency in locus.items()}
            for locus in deme
        ]
        for deme in start
    ]
    return {
        "N": POPULATION_SIZE,
        "ploidy": "haploid",
        "d": DEMES,
        "m": MIGRATION,
        "mu": MUTATION,
        "seed": SEED,
        "loci": [{"locus_id": 1, "length": LOCUS_LENGTH}],
        "engine_backend": "lineal",
        "convergence_statistic": "D",
        "convergence_burn_in": 1,
        "replicate_averaging_window": HORIZON - 1,
        "n_replicates": REPLICATES,
        "stop_batch_early": False,
        "p_0": p_0,
    }


def load_validation_module() -> ModuleType:
    """Import the equilibrium-validation test module by path.

    Returns:
        The imported module.
    """
    spec = importlib.util.spec_from_file_location("equilibrium_validation", TEST_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main(argv: Sequence[str] | None = None) -> int:
    """Print, check, or write the example's configuration.

    Args:
        argv: Command-line arguments, excluding the program name.

    Returns:
        0 on success; 1 when `--check` finds `config.yaml` out of date.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail when config.yaml differs from the derivation",
    )
    mode.add_argument(
        "--write", action="store_true", help="rewrite config.yaml from the derivation"
    )
    args = parser.parse_args(argv)

    module = load_validation_module()
    text = render(build_config(module))
    if args.write:
        CONFIG_PATH.write_text(text, encoding="utf-8")
        return 0
    if args.check:
        current = (
            CONFIG_PATH.read_text(encoding="utf-8") if CONFIG_PATH.is_file() else ""
        )
        if current != text:
            sys.stderr.write(f"{CONFIG_PATH} is out of date; run with --write\n")
            return 1
        return 0

    # Without an option, show the derivation's results and change nothing.
    within_star, between_star = module._identity_fixed_point(
        population_size=POPULATION_SIZE, m=MIGRATION, mu=MUTATION, d=DEMES
    )
    oracle_g_st, oracle_d = module._identities_to_statistics(
        within_star, between_star, DEMES
    )
    sys.stdout.write(text)
    sys.stdout.write(
        f"# predicted equilibrium: G_ST = {oracle_g_st:.6f}, D = {oracle_d:.6f}\n"
    )
    return 0


def render(config: dict[str, Any]) -> str:
    """Return the configuration file's full text.

    Args:
        config: The model keys from `build_config`.

    Returns:
        The labels header followed by the model keys as YAML. Each island's
        `p_0` mapping is written in flow style, wrapped to fit the line
        length the repository's YAML lint allows.
    """
    model = {key: value for key, value in config.items() if key != "p_0"}
    body = yaml.safe_dump(model, sort_keys=False, default_flow_style=False)
    p_0 = yaml.safe_dump(
        {"p_0": config["p_0"]}, sort_keys=False, default_flow_style=None, width=100
    )
    return HEADER + body + p_0


if __name__ == "__main__":
    raise SystemExit(main())
